# Stage 1: Build 
FROM python:3.11-slim AS builder 

WORKDIR /build

RUN apt-get update

COPY vector_indexing/requirements.txt .

# Install build dependencies if necessary
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

RUN apt-get purge -y --auto-remove build-essential cmake g++ && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Stage 2: Runtime
FROM python:3.11-slim

WORKDIR /app
ENV PYTHONPATH=/app

# Copy installed packages from builder
COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages

# Copy the service account key file
# COPY google_key.json /app/google_key.json
ENV GOOGLE_APPLICATION_CREDENTIALS=/app/google_key.json

# Copy application code
COPY common /app/common
COPY vector_indexing /app/vector_indexing

# Set the working directory to the vector_indexing directory
WORKDIR /app/vector_indexing

CMD ["python", "indexing_app.py"]